### ISSUE TITLE
can one use spaces in ``-o`` argument ?

### ISSUE THREAD

**Issue by jfbu** [mgieseki/dvisvgm#73]
This comes from https://github.com/sphinx-doc/sphinx/issues/3835. Typical call by Sphinx can look like this:

```
dvisvgm -o '/pathto/Folder with space/SphinxProject/build/html/_images/math/someshaid.svg' /var/folders/stuff/math.dvi
```

but this gives rise when executed manually to
```
processing of PostScript specials is disabled (Ghostscript not found)
pre-processing DVI file (format 2)
processing page 1
  page size: 267.94pt x 15.2375pt (94.17mm x 5.35538mm)
  page written to ../../Folder\.svg
1 of 1 page converted in 0.310053 seconds
```

which means that the output `svg` is not in expected location. The Sphinx call is in fact via Python subprocess.Popen() with argument like this

```
['dvisvgm', '-o', '/path/bar.svg', '--no-fonts', '/otherpath/foo.dvi']
```

Is there any way to use paths with spaces with ``-o``? (I tried various quoting on the command line with no success). 

If there is no way, then I guess Sphinx extension `imgmath` will have to produce output at same location as the input and copy in a second step to destination.

**Comment by mgieseki** [comment]
According to your [comment](https://github.com/sphinx-doc/sphinx/issues/3835#issuecomment-305606960) in the sphinx ticket, you're using the old version 1.15.1 of dvisvgm. I can indeed reproduce the issue with it. However, the bug has already been fixed in the meantime so that the latest release should work as expected.

**Comment by jfbu** [comment]
Indeed:

```
$ dvisvgm --version
dvisvgm (TeX Live) 1.15.1

s$ cd `dirname $(which dvisvgm)` && pwd -P
/usr/local/texlive/2017/bin/x86_64-darwinlegacy
```

this is with the TeXLive 2017, pretest, on macOS 10.9.5.

On a Linux box with similarly TL2017 I get the version from the man page as

    dvisvgm 1.15.1                    04/19/2016  

but can't execute `dvisvgm` due to 

```
$ dvisvgm --version
dvisvgm: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by dvisvgm)
dvisvgm: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by dvisvgm)
```

but probably don't worry about it: I have no admin rights on this one, can't install anything, and it is a Ubuntu 16.04 install on a weird file system, and it is quite broken, for example gedit doesn't even find system fonts.

But this means that people on TeXLive will still have the problem with TL2017, and TeXLive doesn't usually update binaries during the yearly cycle. Although sometimes they do in case of bugs, should I drop a line on texlive mailing list ?

Anyway, at Sphinx we must support older installations anyhow, so we will have to handle the `-o` parameter otherwise.

Thanks for confirming the issue is there (and the fix already done)!

**Comment by mgieseki** [comment]
As far as I can tell, TL 2017 will provide dvisvgm 2.1.3 for most systems -- at least this version is present in their [svn trunk](https://www.tug.org/svn/texlive/trunk/Build/source/texk/dvisvgm) . There are probably some older operating systems where the latest C++11-bases sources don't build. In these cases dvisvgm 1.15.1 is used as a fallback. Maybe you can get more reliable information on the TL mailing lists (especially the [tlbuild list](http://tug.org/mailman/listinfo/tlbuild)).

Also, MacPorts provides a TL with a more recent dvisvgm (2.1.2) that might be an alternative to the original TL binaries. Nonetheless, as long as the older dvisvgm versions are around, you unfortunately have to find some workaround for the `-o` issue.

**Comment by jfbu** [comment]
indeed got [this](http://tug.org/pipermail/tlbuild/2017q2/003831.html) for my mac os 10.9.5 

> - I didn't build dvisvgm (getting C++11 code to build in a portable
> way is somewhat tricky, I'll see whether I'll bite that bullet next
> year or just drop support for 10.6 and lower).
> 

I have posted a message yet to appear on [tlbuild](http://tug.org/mailman/listinfo/tlbuild) asking for general information.

**Comment by jfbu** [comment]
Did the 1.16 version had the `-o` problem ? because it still does not use C+11, so possibly could be incorporated into TeXLive even before next year for the problematic architectures. If they are gentle enough to build it...

**Comment by mgieseki** [comment]
Yes, 1.16. is also affected. The bug was fixed in 2.1.
Since dvisvgm 1.15.1 doesn't support the recent XeTeX present in TL 2017, I offered to backport the changes to 1.16 a couple of months ago and could have fixed the `-o` issue as well. However, TL doesn't support two different versions as successor of an older binary. Thus, users of older operating systems will still get the dated dvisvgm 1.15.1 that won't be fully functional within TL 2017.
